[package]
name = "calr"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.102"
assert_cmd = "2.2.1"
chrono = {version = "0.4.44", features = ["clock"] }
clap = { version = "4.6.1", features = ["derive"] }
colorize = "0.1.0"
predicates = "3.1.4"
pretty_assertions = "1.4.1"
